
Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
include_path = [cwd]
src = []

if GetDepend(['RT_USING_HELLO']):
    src += ['hello.c']

group = DefineGroup('hello', src, depend = [''], CPPPATH = include_path)

Return('group')


